// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTVcAYPPeCWNrZOoc46OOYfH81zioIIZs',
    appId: '1:438603931578:web:163483cbdfbbe2a6614783',
    messagingSenderId: '438603931578',
    projectId: 'clean-arch-c8777',
    authDomain: 'clean-arch-c8777.firebaseapp.com',
    storageBucket: 'clean-arch-c8777.firebasestorage.app',
    measurementId: 'G-G2WLJL58XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXSIUNpDN2KszM4_yNmPL0nsER5ARLbkQ',
    appId: '1:438603931578:android:02ab3329b3bbe760614783',
    messagingSenderId: '438603931578',
    projectId: 'clean-arch-c8777',
    storageBucket: 'clean-arch-c8777.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqYLe8386Y1Wx3S0XoUbXA83daMd12ecM',
    appId: '1:438603931578:ios:72de7f6e23b9daba614783',
    messagingSenderId: '438603931578',
    projectId: 'clean-arch-c8777',
    storageBucket: 'clean-arch-c8777.firebasestorage.app',
    iosBundleId: 'com.example.cleanArc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqYLe8386Y1Wx3S0XoUbXA83daMd12ecM',
    appId: '1:438603931578:ios:72de7f6e23b9daba614783',
    messagingSenderId: '438603931578',
    projectId: 'clean-arch-c8777',
    storageBucket: 'clean-arch-c8777.firebasestorage.app',
    iosBundleId: 'com.example.cleanArc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTVcAYPPeCWNrZOoc46OOYfH81zioIIZs',
    appId: '1:438603931578:web:6132764a175e3f07614783',
    messagingSenderId: '438603931578',
    projectId: 'clean-arch-c8777',
    authDomain: 'clean-arch-c8777.firebaseapp.com',
    storageBucket: 'clean-arch-c8777.firebasestorage.app',
    measurementId: 'G-PYQTRP3ZVH',
  );
}
