name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - main

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo code
        uses: actions/checkout@v2
      
      - name: Set up JDK 17  # Updated to Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Changed from 11 to 17
          distribution: 'temurin'
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'
          bundler-cache: false
      
      - name: Install Ruby Gems
        run: |
          cd android
          bundle install

      - name: Build and Distribute App
        env:
          FAST_LANE_SECURE: ${{ secrets.FAST_LANE_SECURE }}
        run: |
          cd android
          bundle exec fastlane android firebase_distribution_test